AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS ExecutionRole for tasks'

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
Outputs:
  ExecutionRoleArn:
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: ECSExecutionRoleArn